all: tprc2023-cpan-sec-lightning-talk/index.html perlkohacon-cpan-sec-lightning-talk/index.html nis2-cra-intro/index.html perlkohacon-cpan-sbom-talk/index.html fosdem2024-cpan-sec-talk/index.html fosdem2024-sbom-in-open-source-ecosystems-talk/index.html


tprc2023-cpan-sec-lightning-talk/index.html: tprc2023-cpan-sec-lightning-talk.md
	mdslides tprc2023-cpan-sec-lightning-talk.md --include ../media

perlkohacon-cpan-sec-lightning-talk/index.html: perlkohacon-cpan-sec-lightning-talk.md
	mdslides perlkohacon-cpan-sec-lightning-talk.md --include ../media

fosdem2024-sbom-in-open-source-ecosystems-talk/index.html: fosdem2024-sbom-in-open-source-ecosystems-talk.md
	mdslides fosdem2024-sbom-in-open-source-ecosystems-talk.md --include ../media

fosdem2024-cpan-sec-talk/index.html: fosdem2024-cpan-sec-talk.md
	mdslides fosdem2024-cpan-sec-talk.md --include ../media

perlkohacon-cpan-sbom-talk/index.html: perlkohacon-cpan-sbom-talk.md
	mdslides perlkohacon-cpan-sbom-talk.md --include ../media

nis2-cra-intro/index.html: nis2-cra-intro.md
	mdslides nis2-cra-intro.md --include ../media
